### ISSUE TITLE
 Nugget Error ?

### ISSUE THREAD

**Issue by Muffin-Time** [shlifedev/AmongUsMemory#19]
I'm not sure if I'm doing something wrong (kind of new to coding still) but I get this error when I build

Severity Code Description Project File Line Suppression State Error NuGet Package restore failed for project AmongUsMemory: Unable to find version '1.2.19' of package 'Memory.dll'. C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Memory.dll.1.2.19' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. https://api.nuget.org/v3/index.json: Package 'Memory.dll.1.2.19' is not found on source 'https://api.nuget.org/v3/index.json'. . Please see Error List window for detailed warnings and errors.

I've tried some different things but none seem to work.

**Comment by Ginkoe** [comment]
Grab Memory.dll from AmongUsMemory/bin/debug/Memory.dll and add reference to it instead of pulling it from nuget

**Comment by Muffin-Time** [comment]
> Grab Memory.dll from AmongUsMemory/bin/debug/Memory.dll and add reference to it instead of pulling it from nuget

When I go to do that it either doesn't let me or just says "A reference to the component 'Memory' already exist in the project.

**Comment by Terrain2** [comment]
It appears the issue is that "Memory" is listed as being a dependency from NuGet in this repo, i fixed it by simply removing its entry here, simply just removing the line in this file: https://github.com/shlifedev/AmongUsMemory/blob/d209ababfe2d68c3651513aac5bdce42ba62c159/AmongUsMemory/packages.config#L1-L4 and then i removed the reference and added it back within visual studio (unload the "AmongUsMemory" project before manually editing this file though, then reload and re-add the reference)
