### ISSUE TITLE
How to set red is if impostor

### ISSUE THREAD

**Issue by PixelGM** [shlifedev/AmongUsMemory#37]
So the code is

if (data.PlayerInfo.Value.IsImpostor == 1)

and then what? to set the name to red in game, not in console.

**Comment by oOHiyoriOo** [comment]
iam trying this as well rn so if you come along a way to solve this please tell me.

**Comment by PixelGM** [comment]
> 
> 
> iam trying this as well rn so if you come along a way to solve this please tell me.

i mean i can do print if impostor = 1, then the font to red in console, but not in game.

**Comment by oOHiyoriOo** [comment]
yeah i know i thought about that too.
maybe with the write memory ? when you modify the name itfself? ill try later

**Comment by oOHiyoriOo** [comment]
because it is a unity app i tryed find the unity way of doin it and found this: 
![image](https://user-images.githubusercontent.com/44544317/94903290-e09fab80-0499-11eb-9f16-cae86a8dc68d.png)
so i tryed to do:
```
if(data.PlayerInfo.Value.IsImpostor == 1) {
                            var targetPointer = Utils.GetMemberPointer(data.Instance.nameText,typeof(String),"Name");
                            Cheese.mem.WriteMemory(targetPointer.GetAddress(),"String","<color = red>"+ data.PlayerInfo.Value.PlayerName+ "</color>");
                        }
```
what (for me) didnt took any affect so maybe you can find the mistake ? it at least was supposed to change the name in anyway (append this color thing as string or color it...)

**Comment by PixelGM** [comment]
it did

> 
> 
> because it is a unity app i tryed find the unity way of doin it and found this:
> ![image](https://user-images.githubusercontent.com/44544317/94903290-e09fab80-0499-11eb-9f16-cae86a8dc68d.png)
> so i tryed to do:
> 
> ```
> if(data.PlayerInfo.Value.IsImpostor == 1) {
>                             var targetPointer = Utils.GetMemberPointer(data.Instance.nameText,typeof(String),"Name");
>                             Cheese.mem.WriteMemory(targetPointer.GetAddress(),"String","<color = red>"+ data.PlayerInfo.Value.PlayerName+ "</color>");
>                         }
> ```
> 
> what (for me) didnt took any affect so maybe you can find the mistake ? it at least was supposed to change the name in anyway (append this color thing as string or color it...)

it didnt work...

**Comment by RedLeader167** [comment]
i think it's little different in compiled game

**Comment by oOHiyoriOo** [comment]
Yeah I think as well but it was worth a try iam gonna search it up later today.

**Comment by Aurumaker72** [comment]
> Yeah I think as well but it was worth a try iam gonna search it up later today.

I think (as RedLeader167 said) that in the compiled executable you cant just find strings in memory

**Comment by oOHiyoriOo** [comment]
> > Yeah I think as well but it was worth a try iam gonna search it up later today.
> 
> I think (as RedLeader167 said) that in the compiled executable you cant just find strings in memory

Yeah sure but as u can set the light state etc. U should be able to set the names for urself and prepend a prefix that changes the color.

**Comment by oOHiyoriOo** [comment]
Could this be the solution ? Can't test rn because iam on mobile.
https://stackoverflow.com/questions/29924725/change-color-of-text-during-runtime-unity

**Comment by Aurumaker72** [comment]
> Could this be the solution ? Can't test rn because iam on mobile.
> https://stackoverflow.com/questions/29924725/change-color-of-text-during-runtime-unity

Wouldn't that only be client-side? Also i think the servers only accepts name changes when the round hasn't started yet...

**Comment by DiamondMiner88** [comment]
This repo is to help modify client-side values for among us.
If you're aiming to change your name while in-progress you can only do that client-side since the server doesn't use your name as an identifier once the game has started.

**Comment by PixelGM** [comment]
no, i mean we have to get the list of the Among Us ColorIDs, in this repo, we already have the ColorIDs, but we need the list.

**Comment by oOHiyoriOo** [comment]
> 
> 
> > Could this be the solution ? Can't test rn because iam on mobile.
> > https://stackoverflow.com/questions/29924725/change-color-of-text-during-runtime-unity
> 
> Wouldn't that only be client-side? Also i think the servers only accepts name changes when the round hasn't started yet...

ofc it is client sided !
we can only modify our own Memory not the memory of others (would be a huge security issue!)

**Comment by Devilx86** [comment]
I stumbled upon this repo somehow, but all you need to do is Change PlayerControl->nameText->Color to the color you want it to show in game, see this:
https://github.com/Devilx86/ImpostorModmenu/blob/bb6416d4f0925cbab56da80964dba563ba07f709/app/src/main/cpp/mods.h#L172

**Comment by Devilx86** [comment]
All you need to do is Change PlayerControl->nameText->Color to the color you want it to show in game, see this:
https://github.com/Devilx86/ImpostorModmenu/blob/bb6416d4f0925cbab56da80964dba563ba07f709/app/src/main/cpp/mods.h#L172

**Comment by PixelGM** [comment]
> 
> 
> All you need to do is Change PlayerControl->nameText->Color to the color you want it to show in game, see this:
> https://github.com/Devilx86/ImpostorModmenu/blob/bb6416d4f0925cbab56da80964dba563ba07f709/app/src/main/cpp/mods.h#L172

wait u have the source for impostormodmenu? lol

**Comment by Devilx86** [comment]
> > All you need to do is Change PlayerControl->nameText->Color to the color you want it to show in game, see this:
> > https://github.com/Devilx86/ImpostorModmenu/blob/bb6416d4f0925cbab56da80964dba563ba07f709/app/src/main/cpp/mods.h#L172
> 
> wait u have the source for impostormodmenu? lol

I wrote the mod menu, its been open source since the release lol.

**Comment by oOHiyoriOo** [comment]
> > > All you need to do is Change PlayerControl->nameText->Color to the color you want it to show in game, see this:
> > > https://github.com/Devilx86/ImpostorModmenu/blob/bb6416d4f0925cbab56da80964dba563ba07f709/app/src/main/cpp/mods.h#L172
> > 
> > 
> > wait u have the source for impostormodmenu? lol
> 
> I wrote the mod menu, its been open source since its first release.

is this still c# ? iam not advanced in c# so i cant tell actually... it looks like c to me :/

**Comment by Devilx86** [comment]
Its not C#, but the idea is the same, What I am saying has not been tested but this should work for you in C#.

First note that the structure addresses could be different on PC, I am modding on android and I will explain with that give it a try.
I took a look at PlayerInfo.xml for you and it looks like what is defined there is the GameData_PlayerInfo_o struct see in IDA. Now what you want to do is access PlayerControl_o-> nameText->Color. Once you do this You can change rgba from that Color struct.
if you see in IDA, the GameData Struct is 0x50 the following is the structure offsets on android:
00000000 GameData_PlayerInfo_o struc ; (sizeof=0x50, align=0x8, copyof_4076)
00000000 klass          ; offset
00000008 monitor     ; offset
00000010 PlayerId     
00000017                    ; Nothing till here just padding for structure alignment
00000018 PlayerName    ; offset
00000020 ColorId    
00000023                  ; Nothing till here just padding for structure alignment
00000024 HatId    
00000028 PetId    
0000002C SkinId  
00000030 Disconnected 
00000037                 ; Nothing till here just padding for structure alignment
00000038 Tasks
00000040 IsImpostor
00000041 IsDead 
00000047                ; Nothing till here just padding for structure alignment
00000048 _object                    ; this is PlayerControl_o
00000050 GameData_PlayerInfo_o ends

So in this project, Compare this with PlayerInfo.xml and you will see offsets are slightly different probably because PC. The _object at offset 50 on Android is a pointer to PlayerControl_o struct, see if that pointer exists in the PC version too, Chances are its there maybe slightly different offset? but find that and declare that in PlayerInfo.xml.
In PlayerControl.xml you can see at offset 76 for PC there is nameText access this to access Color and then Color is a struct with rgba modify that. Good Luck! I hope this helps.

**Comment by Devilx86** [comment]
Its not C#, but the idea is the same. See PlayerInfo.cs, the last variable _object is a pointer to PlayerControl_o see in IDA. Now what you want to do is access PlayerControl_o-> nameText->Color i.e For you on PC and however you write it in C#, access PlayerInfo->_object->nameText->Color. Color has 3 members rgba change that to whatever rgba you want the player names to be.

**Comment by PixelGM** [comment]
> 
> 
> Its not C#, but the idea is the same. See PlayerInfo.cs, the last variable _object is a pointer to PlayerControl_o. Now what you want to do is access PlayerControl_o-> nameText->Color i.e For you on PC and however you write it in C#, access PlayerInfo->_object->nameText->Color.
> Color has 3 members rgba change that to whatever rgba you want the player names to be.
> 
> See how killtimer is overwritten in this project. Killtimer is actually PlayerInfo->_object->killtimer so modify that to read
> PlayerInfo->_object->nameText which has Color member in it.

so i do like PlayerInfo->_object->nameText->Color(255, 0, 0, 0.8) //This is red

**Comment by oOHiyoriOo** [comment]
thy I'll take a look into it later when iam home.

**Comment by Devilx86** [comment]
> > Its not C#, but the idea is the same. See PlayerInfo.cs, the last variable _object is a pointer to PlayerControl_o. Now what you want to do is access PlayerControl_o-> nameText->Color i.e For you on PC and however you write it in C#, access PlayerInfo->_object->nameText->Color.
> > Color has 3 members rgba change that to whatever rgba you want the player names to be.
> > See how killtimer is overwritten in this project. Killtimer is actually PlayerInfo->_object->killtimer so modify that to read
> > PlayerInfo->_object->nameText which has Color member in it.
> 
> so i do like this?
> PlayerInfo->_object->nameText->Color(255, 0, 0, 0.8) //This is red

Sorry I am of no help anymore, Don't know if thats correct since its in C#, but yes that is the structure you want to access, try adding that to the update loop and if it works then thats it, otherwise probably something wrong with the way the you access Color structure.

**Comment by shlifedev** [comment]
guys, i added set name text color features. use this.
@PixelGM @oOHiyoriOo 
```cs

     public void WriteMemory_SetNameTextColor(Color value)
        {
            var targetPointer = Utils.GetMemberPointer(Instance.nameText, typeof(TextRenderer), "Color");
            Cheese.mem.WriteMemory(targetPointer.GetAddress(), "float", value.r.ToString("0.0"));
            Cheese.mem.WriteMemory((targetPointer+4).GetAddress(), "float", value.g.ToString("0.0"));
            Cheese.mem.WriteMemory((targetPointer+8).GetAddress(), "float", value.b.ToString("0.0"));
            Cheese.mem.WriteMemory((targetPointer+12).GetAddress(), "float", value.a.ToString("0.0"));
        }

```
