### ISSUE TITLE
What is ShipStatus.DirtyBits?

### ISSUE THREAD

**Issue by EastArctica** [shlifedev/AmongUsMemory#45]
Sorry if this has been answered before but what is ShipStatus.DirtyBits, its a uint but its odd because sometimes its 0 and sometimes its a value.

**Comment by KMcNickel** [comment]
Having done no research into this variable itself and basing it on general knowledge, I would guess that value indicates to  the program that some part of the ship status has changed, this allows the program to only need to look at the single variable (and see if it is 0 or not) instead of constantly scanning every value and checking for a change (which would require knowledge of the old value) or acting upon the current value every time its scanned. The actual value of the variable could be used to indicate what has changed.

Useful when the value of the variables in the struct don't change much.

**Comment by EastArctica** [comment]
Interesting, Okay thanks!
